export const seedData = [
    {
        "name": "Nativo",
        "phoneNumber": "5629000072",
        "cashApp": "$NativoHolmes",
        "#": "1",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Nativo #1",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Shereese",
        "phoneNumber": "9123181996",
        "cashApp": "$ShereeseBerry",
        "#": "2",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Shereese #2 #153 #225",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Chantel Moore",
        "phoneNumber": "2484617659",
        "cashApp": "$Chantel2014",
        "#": "3",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Chantel #3 #75 #260",
        "Admin Amount Paid": "$30 "
        },
        {
        "name": "Charlie",
        "phoneNumber": "7134430687",
        "cashApp": "$CharlieBPlus3",
        "#": "4",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Charlie #4",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Ming",
        "phoneNumber": "2819258166",
        "cashApp": "$Mingsking",
        "#": "5",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Ming #5",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Chrissy",
        "phoneNumber": "7209303556",
        "cashApp": "$Chrissyjg18",
        "#": "6",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Chrissy #6",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Tiapughtalks",
        "phoneNumber": "2174541588",
        "cashApp": "$tiapughtalks",
        "#": "7",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Tia #7",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Skye's Life",
        "phoneNumber": "3366902733",
        "cashApp": "$skye88",
        "#": "8",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Skye #8 Mya #175 Mattie #332",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "India",
        "phoneNumber": "5132800756",
        "cashApp": "$Indy621",
        "#": "9",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "India ($Indy621) #9",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Sasha Beechers",
        "phoneNumber": "7542441623",
        "cashApp": "$TheBeechers",
        "#": "10",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "SashaB #10 / Seth #165 /Othneil#111",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Evon",
        "phoneNumber": "6086286158",
        "cashApp": "$evonfidley",
        "#": "11",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Evon Findley #11",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Sophia Calloway",
        "phoneNumber": "9044956893",
        "cashApp": "$Scalloway83",
        "#": "12",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Sophia #12 Jada #145 Destine #171",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Crystal Williams",
        "phoneNumber": "8172988535",
        "cashApp": "$mrswilliams0714",
        "#": "13",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Crystal W #13 #124 #142",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Poohda",
        "phoneNumber": "2106193648",
        "cashApp": "$gorgeouszLex",
        "#": "14",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Poohda #14",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Sharia H",
        "phoneNumber": "6162927635",
        "cashApp": "$sjudyy",
        "#": "15",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Sharia #15 #201",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Nae Dubose",
        "phoneNumber": "9092050586",
        "cashApp": "$Naedee",
        "#": "16",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Naedee #16",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Gina (1619)",
        "phoneNumber": "3473239003",
        "cashApp": "$gigee2bc",
        "#": "17",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Gina #17 & 164 & 261",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Dominique",
        "phoneNumber": "5042475538",
        "cashApp": "$NikkiBB29",
        "#": "18",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Dominique #18 $NikkiBB29",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Akilah",
        "phoneNumber": "8572225034",
        "cashApp": "$Akilahsherie",
        "#": "19",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Akilah#19 / Zack#157",
        "Admin Amount Paid": "$50 "
        },
        {
        "name": "Travis B",
        "phoneNumber": "8703298940",
        "cashApp": "$Darkprincelife51",
        "#": "20",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Travis B #20",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Tarence Emerson",
        "phoneNumber": "8703298940",
        "cashApp": "$strongarms52",
        "#": "21",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Tarence#21#441",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Amiee Beasley",
        "phoneNumber": "3462675243",
        "cashApp": "$amieeb4",
        "#": "22",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Amiee #22",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "N'dea Jacobs",
        "phoneNumber": "3127744474",
        "cashApp": "$NDeaDiamond",
        "#": "23",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "N'Dea Jacobs #23",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Albert Salcedo",
        "phoneNumber": "6097448341",
        "cashApp": "$ScarfaceDaDon",
        "Referred by": "Krissy #114",
        "#": "24",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "ScarfaceDaDon #24",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Ashley Gates",
        "phoneNumber": "2513828564",
        "cashApp": "$ANicoleGa",
        "#": "25",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Ashley #25 Jeremiah #102 $ANicoleGa",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": " Crystal Tolentino (Leilani)",
        "phoneNumber": "5613989910",
        "cashApp": "$lei561lani",
        "#": "26",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Crystal #26 Mike #395",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Crystal Macklin",
        "phoneNumber": "708-829-5468",
        "cashApp": "$MzCrystal43",
        "#": "27",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Crystal Macklin #27 / #172",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Jasmine (Jazz)",
        "phoneNumber": "3345615622",
        "cashApp": "$bosscertified365",
        "Referred by": "Skye #8",
        "#": "28",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Jazz #28",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Lexs Mcfadden",
        "phoneNumber": "8034774771",
        "cashApp": "$alexus0405",
        "#": "29",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Lexs #29 Mcfadden",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Melanin A",
        "phoneNumber": "4434130445",
        "cashApp": "$wonderland3",
        "#": "30",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "#30 Melanin A.",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Yanerah",
        "phoneNumber": "9374325204",
        "cashApp": "$reallyjustjess",
        "Referred by": "Skye #8",
        "#": "31",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Yanerah 31",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Shon",
        "cashApp": "$Belizeanbeauty86",
        "#": "32",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Shon #32/262/Jennette #152",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Curtis Berry",
        "phoneNumber": "4706633305",
        "cashApp": "$c19m84b",
        "#": "33",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "curtis #33",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Shabazz",
        "phoneNumber": "9045269434",
        "cashApp": "$luvmenih",
        "#": "34",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Shabazz #34-#230",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Sierra Rios",
        "phoneNumber": "2106082165",
        "cashApp": "$sierrarios1215",
        "#": "35",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Sierra Rios #35 #407",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Tobakeion",
        "phoneNumber": "6018806472",
        "cashApp": "$tobak",
        "Referred by": "Skye #8",
        "#": "36",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Tobakeion036 252 B",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "MaryAnn (Chelle)",
        "phoneNumber": "3307943712",
        "cashApp": "$cheLLe330",
        "#": "37",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "MaryAnn #37\"Chelle\"",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Tara L",
        "phoneNumber": "9176878662",
        "cashApp": "$DivaDiamond2",
        "Referred by": "Skye #8",
        "#": "38",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Tara L-38-DivaDiamond2",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Nadia Frederick",
        "cashApp": "$island101",
        "#": "39",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Nadia #39 malik#195",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Elayna",
        "phoneNumber": "9379869188",
        "cashApp": "$ninobug",
        "#": "40",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Elayna #40 $ninobug",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Melissa",
        "phoneNumber": "2687800671",
        "cashApp": "$MelAri6",
        "#": "41",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Melissa #41",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Neisha",
        "phoneNumber": "3235354355",
        "cashApp": "$JamiNeisha",
        "#": "42",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "NeishaJami #42#135",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Maine Nicole",
        "phoneNumber": "740-910-2722",
        "cashApp": "$MaineNicole",
        "#": "43",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Maine Nicole \"emoji\" #43",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Mesha",
        "phoneNumber": "2105893104",
        "cashApp": "$ohhthatsmesha",
        "#": "44",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Jade ",
        "phoneNumber": "9312781307",
        "cashApp": "$jadCh",
        "#": "45",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Jade #45",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Kimika Bridges",
        "phoneNumber": "4439444030",
        "cashApp": "$Kimika82",
        "#": "46",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Kimika B #46",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Gevon",
        "phoneNumber": "3477022220",
        "cashApp": "$Shynayasky",
        "#": "47",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Hope Patterson",
        "phoneNumber": "8434762533",
        "cashApp": "$HopeSierra",
        "#": "48",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Hope P #48",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Cailey Spencer",
        "phoneNumber": "2534410229",
        "cashApp": "$Caileylynn91",
        "#": "49",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Cailey #49",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Geneava Danielson",
        "phoneNumber": "4073101399",
        "cashApp": "$itsneevaxo",
        "#": "50",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Geneava Danielson #50",
        "Admin Amount Paid": "$50 "
        },
        {
        "name": "Quashon Russell (Ace)",
        "phoneNumber": "9122553519",
        "cashApp": "$GQ424",
        "Referred by": "SHEREESE #2",
        "#": "51",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Ace #51",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Ruth Diallo",
        "phoneNumber": "3479946747",
        "cashApp": "$RuthD100",
        "#": "52",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "RuthDiallo#52,119,271,454",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Cathy",
        "phoneNumber": "2533590571",
        "cashApp": "$cb0304",
        "#": "53",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Cathy B #53 #466 #467",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Shontee",
        "phoneNumber": "3142303449",
        "cashApp": "$7angelsvw",
        "#": "54",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Shontee#54 Sean#473 Eshirah#474",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Jacari",
        "phoneNumber": "9123149964",
        "cashApp": "$Tynisha8732",
        "Referred by": "(Referral: Child #132)",
        "#": "55",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Alisa B",
        "phoneNumber": "3129614520",
        "cashApp": "$alisabaron",
        "#": "56",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Alisha 56 339",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Red Williams",
        "phoneNumber": "8177974578",
        "cashApp": "$Flyredcash",
        "#": "57",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Red #57 Williams",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Elle",
        "phoneNumber": "3478458157",
        "cashApp": "$Elle1004",
        "#": "58",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Elle #58",
        "Admin Amount Paid": "$25 "
        },
        {
        "name": "Meya",
        "phoneNumber": "7249786205",
        "cashApp": "$lanelltoo",
        "Referred by": "Morissa J (Child)",
        "#": "59",
        "adminFee": "TRUE",
        "investment": "TRUE",
        "cashOut": "TRUE",
        "Notes- Telegram Name": "Morissa J. #137 Meya #59",
        "Admin Amount Paid": "$70 "
        },
       
]